### PR TITLE
Modified bench.rs for geom_smooth to work and added sort_unstable from rust stdlib

### PR DESCRIPTION
**Pull request by arnabanimesh**
Now you can do benchmark by controlling the minimum and the maximum number of elements, and the geom_smooth will always work due to the availability of data points.

Also, there is a faster implementation of rust sort which is known in `stdlib` as `sort_unstable`. Added the same for comparison purposes.

### CODE REVIEW

**Comment by jonhoo** [comment]
The addition of `sort_unstable` is a good one! Would you mind submitting that as a separate PR?

I'm not sure I understand the reason for `MIN_ELEMENT` and `MAX_ELEMENT`? Why are those necessary?

**Comment by arnabanimesh** [comment]
Mainly it is to make the geom_smooth work and control the interval within which you want to do benchmarks. Geom_smooth requires values at some intervals. If the MIN_ELEMENT is 80, and MAX_ELEMENT is 500, the list generated will be [80, 90, 100, 200, 300, 400, 500], thus geom_smooth will generate some nice looking plots. You can change MAX_ELEMENT and MIN_ELEMENT to do benchmarks as per your needs.

It was hard for me to read geom_point, hence I did the change. An example plot: 
[Rplots.pdf](https://github.com/jonhoo/orst/files/5551427/Rplots.pdf)

**Comment by arnabanimesh** [comment]
> The addition of `sort_unstable` is a good one! Would you mind submitting that as a separate PR?
> 
> I'm not sure I understand the reason for `MIN_ELEMENT` and `MAX_ELEMENT`? Why are those necessary?

Submitted a separate PR for `sort_unstable`

**Comment by jonhoo** [comment]
Hmm, looks like this accidentally got marked as merged?

**Pull request merged**
